spring.application.name=lore

spring.datasource.url=jdbc:postgresql://ep-misty-forest-a1j6sa9f-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_ATbK0GQX6Imy
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true 
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.springframework.core.env=DEBUG
